// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:81755316-3945-4595-b332-7186b55351d8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_u4d4sILpC",
    "aws_user_pools_web_client_id": "34k8arc2h6rocnbv0e2uor0oc6",
    "oauth": {}
};


export default awsmobile;
